#!/bin/sh

# Configure PATH so that we can access our scripts below
PATH=$PATH:~/.xmonad/bin

# Configure X
#xsetroot -cursor_name left_ptr &
#xrdb -merge ~/.Xdefaults &

# Remap caps lock to backspace
#setxkbmap -option caps:backspace
#setxkbmap -option shift:both_capslock
#xmodmap -e "clear Lock"

# Start a window compositor. This ensures Google Chrome paints correctly.
xcompmgr -n &

# Start the system tray
#tray &

# Start two terminals
gnome-terminal &
gnome-terminal &
gnome-terminal &

# Start a browser
firefox &

keepassx &
nextcloud &
xscreensaver &
